### ISSUE TITLE
PHP 7.3 compatiblity

### ISSUE THREAD

**Issue by peterjaap** [ho-nl/magento2-ReachDigital_TestFramework#7]
The composer.json constraints it on 7.2. But M2.3.3 now supports 7.3 so I'd like to upgrade and use this module.

**Comment by Vinai** [comment]
Bump for 7.4 please

**Comment by Vinai** [comment]
Reference https://github.com/ho-nl/magento2-ReachDigital_TestFramework/pull/8

**Comment by Vinai** [comment]
Maybe close this issue and open a new one regarding PHP 7.4?
