### ISSUE TITLE
Release supporting PHP 7.3

### ISSUE THREAD

**Issue by Vinai** [ho-nl/magento2-ReachDigital_TestFramework#9]
Could you please tag a release with the composer.json that supports PHP 7.3?
Thank you!

**Comment by hws47a** [comment]
+1

**Comment by dimitar-ivanov-tryzens** [comment]
+1,
sure dev-master works but it would be nicer to have a tag.
Thanks for the awesome soft.

**Comment by PascalBrouwers** [comment]
@Vinai starting from 1.1.1 it allows PHP 7.3 now.
